In [1]:
import numpy as np

a=[30,40,20],[30,30,50]
arr=np.array(a)
print(arr)
print(arr.shape) #rows, coloums
print(len(arr)) #number or nested values
print(np.size(arr)) #number of size
print(type(arr)) #type of variable
print(arr.dtype) #datatype of array
print(arr.astype(float)) #converction of atatype
print(arr.astype(str))

[[30 40 20]
 [30 30 50]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int64
[[30. 40. 20.]
 [30. 30. 50.]]
[['30' '40' '20']
 ['30' '30' '50']]


In [2]:
##math and operatio with function 

arr1 = np.array([[30,30,40],[40,20,29]])
arr2 = np.array([[40,50,20],[30,50,10]])
print(arr1+arr2)
print(np.add(arr1, arr2))
print("```````")

print(arr1-arr2)
print(np.subtract(arr1, arr2))
print("```````")

print(arr1*arr2)
print(np.multiply(arr1, arr2))
print("```````")

print(arr1/arr2)
print(np.divide(arr1, arr2))
print("```````")

arr3 = np.array([3])
print(np.power(arr1,arr3))
print("```````")

arr4 = np.array([64000, 8000, 24389])
print(np.sqrt(arr4).astype(int))
#print(astype())

[[70 80 60]
 [70 70 39]]
[[70 80 60]
 [70 70 39]]
```````
[[-10 -20  20]
 [ 10 -30  19]]
[[-10 -20  20]
 [ 10 -30  19]]
```````
[[1200 1500  800]
 [1200 1000  290]]
[[1200 1500  800]
 [1200 1000  290]]
```````
[[0.75       0.6        2.        ]
 [1.33333333 0.4        2.9       ]]
[[0.75       0.6        2.        ]
 [1.33333333 0.4        2.9       ]]
```````
[[27000 27000 64000]
 [64000  8000 24389]]
```````
[252  89 156]


In [3]:
##combining and spliting array

## concatenate 

arr1 = np.array([2,5,4,1,6,3,2])
arr2 = np.array([2,5,4,1,6,3,2])
print(np.concatenate([arr1,arr2]))
print("```````")

#axis 1 Horizontal 2 vertical
arr3 = np.array([[2,5,4],[1,6,3]])
arr4 = np.array([[2,5,4],[1,6,3]])

print(np.concatenate([arr3,arr4]))
print("```````")
print(np.concatenate([arr3, arr4], axis =0))
print("```````")
print(np.concatenate([arr3, arr4], axis =1))
print("```````")

print(np.hstack([arr3,arr4])) ##horizontal concatenation
print("```````")

print(np.vstack([arr3,arr4])) ##vertical concatenation
print("```````")

## spliting

arr5 =np.array([5,4,6,2,4,8])
print(np.array_split(arr5,3))
print("```````")
## or
arr5a = np.array_split(arr5, 3) 
print("index 0",arr5a[0]) ##index
print("index 1",arr5a[1]) ##index
print("index 2",arr5a[2]) ##index
print("```````")

[2 5 4 1 6 3 2 2 5 4 1 6 3 2]
```````
[[2 5 4]
 [1 6 3]
 [2 5 4]
 [1 6 3]]
```````
[[2 5 4]
 [1 6 3]
 [2 5 4]
 [1 6 3]]
```````
[[2 5 4 2 5 4]
 [1 6 3 1 6 3]]
```````
[[2 5 4 2 5 4]
 [1 6 3 1 6 3]]
```````
[[2 5 4]
 [1 6 3]
 [2 5 4]
 [1 6 3]]
```````
[array([5, 4]), array([6, 2]), array([4, 8])]
```````
index 0 [5 4]
index 1 [6 2]
index 2 [4 8]
```````


In [4]:
##add and remove element on array
''"""
. np.append (h, g) - Append items to an array
. np.insert (a, 1, 5) - Inserts items in an array
. np.delete (a, [1]) - Delete items from an array
"""
arr=np.array([2,5,4,7,8,5,6])
print(np.append(arr,7))
print(np.append(arr,[10, 54]))
print("```````")

print(np.insert(arr, 2, 20)) ## (which array, which index, what to add)
print("```````")

arre=np.array([[5,4],[5,6]])
print(np.insert(a,1,[50,100], axis=1))
print("```````")
print(np.insert(a,[1,3],[70,90], axis=1))
print("```````")

print(np.delete(arr, 1))
print("```````")

print(arre)
print("```````")

print(np.delete(arre,1, axis=0))
print("```````")

print(np.delete(arre,1, axis=1))


[2 5 4 7 8 5 6 7]
[ 2  5  4  7  8  5  6 10 54]
```````
[ 2  5 20  4  7  8  5  6]
```````
[[ 30  50  40  20]
 [ 30 100  30  50]]
```````
[[30 70 40 20 90]
 [30 70 30 50 90]]
```````
[2 4 7 8 5 6]
```````
[[5 4]
 [5 6]]
```````
[[5 4]]
```````
[[5]
 [5]]
