In [66]:
import numpy as np
import statistics as stats

ar = np.array([[5,2,5,7],[8,9,4,6]])

print(np.sort(ar))
print("~~~~~~~~")

##filter => existing array, how to find new array from existing array
arr =np.array([8,7,5,4,9,7,5,2,1,5,7,89,56])
s= np.where(arr % 2==2) ##filter (''Where'')<= keyword
print(s)
print("~~~~~~~~")

arr2=np.array([2,3,4,5,6]) 
filyteredArray=[True, False, True, False,True]
##arr2 index == filyteredArray
new=arr2[filyteredArray]
print(new)
print("~~~~~~~~")

filyteredArray=arr2>3
new=arr2[filyteredArray]
print(new)
print("~~~~~~~~")

filyteredArray=arr2%2
new=arr2[filyteredArray]
print(new)
print("~~~~~~~~")


arr=np.array([1,2,3,4,5,6,7,8,9])
ss=np.searchsorted(arr, 7)
print(ss)
print("~~~~~~~~")



[[2 5 5 7]
 [4 6 8 9]]
~~~~~~~~
(array([], dtype=int64),)
~~~~~~~~
[2 4 6]
~~~~~~~~
[4 5 6]
~~~~~~~~
[2 3 2 3 2]
~~~~~~~~
6
~~~~~~~~


In [67]:
##Aggregating function 

arr1=np.array([20,30,40,50,62])

print(np.sum(arr1))
print("~~~~~~~~")

print(np.size(arr1))
print(np.mean(arr1))
print(np.cumsum(arr1)) ##[a, a+b, a+b+c, a+b+c+d]
print(np.cumprod(arr1)) ##[1, 2, 6, 24, 120] [1, 1*2, 1*2*3, 1*2*3*4, 1*2*3*4*5].
print("~~~~~~~~")

a = [109,150,199,200,250,130]
b = [10,50,30,40,30,10]

price=np.array(a)
qunatity =np.array(b)

print(price, "\n", qunatity)
print("~~~~~~~~")
print(np.cumprod([price, qunatity], axis=0))
print(np.sum(price*qunatity))


202
~~~~~~~~
5
40.4
[ 20  50  90 140 202]
[      20      600    24000  1200000 74400000]
~~~~~~~~
[109 150 199 200 250 130] 
 [10 50 30 40 30 10]
~~~~~~~~
[[ 109  150  199  200  250  130]
 [1090 7500 5970 8000 7500 1300]]
31360


In [68]:
##Statistical function 
backed_frrd=[200,300,150,130,200,280,188,170,188]
a=np.array(backed_frrd)
print(np.mean(a)) ##sum of all value/ num of value

print(np.median(a)) ##sorted ordered "center" value
print(stats.mode(a)) ##he value that appears most frequently in a data set
print(np.std(a)) ##standard deviation of elements in an array
print(np.var(a)) ##variance of elements in a given array along a specified axis



200.66666666666666
188.0
200
52.687759489277965
2776.0


In [69]:
##  -1 represents inversely proportation relationship
## 1 represent proportion relationship 
## 0 means no relations

## help's on "Negative Correlation"
jobs = [30,450,40,10,30,50]
application =[100,120,70,100,120,112]

print(np.corrcoef(jobs, application))

[[1.         0.42082301]
 [0.42082301 1.        ]]
